version: "3"

services:
  danmaku:
    image: registry.hanada.info/tamersunion/danmaku:2.1.2
    build:
      context: .
      args:
        DANMAKU_VERSION: 2.1.2
    container_name: danmaku
    restart: unless-stopped
    volumes:
      - "/usr/local/danmaku/appsettings.yml:/usr/local/danmaku/appsettings.yml"
    ports:
      - "127.0.0.1:13009:80"
    depends_on:
      - danmaku-postgres

  danmaku-postgres:
    image: dockerhub.hanada.info/library/postgres:13
    container_name: danmaku-postgres
    restart: unless-stopped
    volumes:
      - "/usr/local/danmaku/database:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: 'danmaku'
      POSTGRES_PASSWORD: 'danmaku'
      POSTGRES_DB: 'danmaku'
      PGDATA: /var/lib/postgresql/data/pgdata
