version: "3"

services:
  danmaku:
    image: registry.hanada.info/tamersunion/danmaku:2.9.2
    build:
      context: .
      args:
        DANMAKU_VERSION: 2.9.2
    container_name: danmaku
    restart: unless-stopped
    volumes:
      - "/usr/local/danmaku/appsettings.json:/usr/local/danmaku/appsettings.json"
    ports:
      - "127.0.0.1:13009:80"
    depends_on:
      - danmaku-postgres
      - danmaku-redis

  danmaku-postgres:
    image: dockerhub.hanada.info/library/postgres:13
    container_name: danmaku-postgres
    restart: unless-stopped
    volumes:
      - "/usr/local/danmaku/database:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: 'danmaku'
      POSTGRES_PASSWORD: 'danmaku'
      POSTGRES_DB: 'danmaku'
      PGDATA: /var/lib/postgresql/data/pgdata

  danmaku-redis:
    image: dockerhub.hanada.info/library/redis:8-alpine
    container_name: danmaku-redis
    restart: unless-stopped
    volumes:
      - "/usr/local/danmaku/redis:/data:Z"
    command: ["redis-server", "--appendonly", "yes"]
