KestrelSettings:
  Host: 127.0.0.1
  Port: 5000
  UnixSocketPath: "/tmp/danmaku.sock"
WithOrigins:
  - "*"
LiveWithOrigins:
  - http://localhost
  - http://localhost:4000
AdminWithOrigins:
  - http://localhost:5000
DanmakuSql:
  Sql: 0
  Host: 127.0.0.1
  Port: 0
  UserName: danmaku
  PassWord: danmaku
  DataBase: danmaku
  PoolSize: 16
Admin:
  User: tamers
  Password: "000000"
  MaxAge: 60
BiliBiliSetting:
  Cookie: ""
  CidCacheTime: 168
  DanmakuCacheTime: 12
