package store

import (
	"context"
	"crypto/md5"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/url"
	"strings"
	"time"

	"git.hanada.info/tamersunion/danmaku/internal/config"
	"git.hanada.info/tamersunion/danmaku/internal/domain"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Postgres struct {
	pool  *pgxpool.Pool
	admin config.AdminSettings
}

func Open(ctx context.Context, cfg config.Config) (*Postgres, error) {
	poolConfig, err := pgxpool.ParseConfig(cfg.DanmakuSQL.ConnectionString())
	if err != nil {
		return nil, fmt.Errorf("parse PostgreSQL configuration: %w", err)
	}
	poolConfig.MaxConns = cfg.DanmakuSQL.PoolSize
	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		return nil, fmt.Errorf("open PostgreSQL pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("connect to PostgreSQL: %w", err)
	}
	return &Postgres{pool: pool, admin: cfg.Admin}, nil
}

func (p *Postgres) Close() { p.pool.Close() }

func (p *Postgres) Initialize(ctx context.Context) error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS "User" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"Name" character varying(16) NOT NULL,
			"PassWord" text NOT NULL,
			"Salt" text NOT NULL,
			"Role" integer NOT NULL,
			"PhoneNumber" text NULL,
			"Email" text NULL,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			"UpdateTime" timestamp(3) without time zone NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS "Video" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"Vid" character varying(36) NOT NULL,
			"Referer" jsonb NULL,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			"UpDateTime" timestamp(3) without time zone NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS "Danmu" (
			"Id" uuid NOT NULL PRIMARY KEY,
			"Vid" character varying(36) NOT NULL,
			"Data" jsonb NOT NULL,
			"Ip" inet NULL,
			"IsDelete" boolean NOT NULL DEFAULT FALSE,
			"VideoId" integer NULL,
			"CreateTime" timestamp(0) without time zone NOT NULL,
			"UpdateTime" timestamp(0) without time zone NOT NULL,
			CONSTRAINT "FK_Danmu_Video_VideoId" FOREIGN KEY ("VideoId") REFERENCES "Video" ("Id") ON DELETE RESTRICT
		)`,
		`CREATE TABLE IF NOT EXISTS "HttpClientCache" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"Key" text NOT NULL,
			"Value" bytea NULL,
			"TimeStamp" bigint NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS "IX_Danmu_Vid_IsDelete" ON "Danmu" ("Vid", "IsDelete")`,
		`CREATE INDEX IF NOT EXISTS "IX_Danmu_VideoId" ON "Danmu" ("VideoId")`,
		`CREATE INDEX IF NOT EXISTS "IX_HttpClientCache_Key" ON "HttpClientCache" USING hash ("Key")`,
		`DO $$ BEGIN IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='UpDateTime') THEN ALTER TABLE "User" RENAME COLUMN "UpDateTime" TO "UpdateTime"; END IF; END $$`,
	}
	for _, statement := range statements {
		if _, err := p.pool.Exec(ctx, statement); err != nil {
			return fmt.Errorf("initialize PostgreSQL schema: %w", err)
		}
	}

	var count int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "User"`).Scan(&count); err != nil {
		return fmt.Errorf("count users: %w", err)
	}
	if count == 0 {
		salt, err := randomString(6)
		if err != nil {
			return err
		}
		now := time.Now().UTC()
		password := saltedMD5(md5String(p.admin.Password), salt)
		_, err = p.pool.Exec(ctx, `INSERT INTO "User" ("Name", "PassWord", "Salt", "Role", "CreateTime", "UpdateTime") VALUES ($1,$2,$3,1,$4,$4)`, p.admin.User, password, salt, now)
		if err != nil {
			return fmt.Errorf("create initial administrator: %w", err)
		}
	}
	return nil
}

func (p *Postgres) QueryByVid(ctx context.Context, vid string) ([]domain.DanmakuData, error) {
	rows, err := p.pool.Query(ctx, `SELECT "Data" FROM "Danmu" WHERE "Vid"=$1 AND NOT "IsDelete"`, vid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := make([]domain.DanmakuData, 0)
	for rows.Next() {
		var raw []byte
		if err := rows.Scan(&raw); err != nil {
			return nil, err
		}
		data := domain.NewDanmakuData()
		if err := json.Unmarshal(raw, &data); err != nil {
			return nil, fmt.Errorf("decode Danmu.Data: %w", err)
		}
		result = append(result, data)
	}
	return result, rows.Err()
}

func (p *Postgres) Insert(ctx context.Context, vid string, data domain.DanmakuData, ip net.IP, referer domain.Referer) error {
	videoID, err := p.findOrInsertVideo(ctx, vid, referer)
	if err != nil {
		return err
	}
	raw, err := domain.MarshalDBData(data)
	if err != nil {
		return err
	}
	id, err := randomUUID()
	if err != nil {
		return err
	}
	now := time.Now().UTC().Truncate(time.Second)
	var ipValue any
	if ip != nil {
		ipValue = ip.String()
	}
	_, err = p.pool.Exec(ctx, `INSERT INTO "Danmu" ("Id","Vid","Data","Ip","IsDelete","VideoId","CreateTime","UpdateTime") VALUES ($1,$2,$3,$4,FALSE,$5,$6,$6)`, id, vid, raw, ipValue, videoID, now)
	return err
}

func (p *Postgres) findOrInsertVideo(ctx context.Context, vid string, referer domain.Referer) (int, error) {
	rows, err := p.pool.Query(ctx, `SELECT "Id", "Referer" FROM "Video" WHERE "Vid"=$1`, vid)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	for rows.Next() {
		var id int
		var raw []byte
		if err := rows.Scan(&id, &raw); err != nil {
			return 0, err
		}
		var existing domain.Referer
		if json.Unmarshal(raw, &existing) == nil && existing.Protocol == referer.Protocol && existing.Host == referer.Host && existing.Path == referer.Path && existing.Query == referer.Query {
			return id, nil
		}
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}
	raw, err := domain.MarshalDBReferer(referer)
	if err != nil {
		return 0, err
	}
	now := time.Now().UTC().Truncate(time.Millisecond)
	var id int
	err = p.pool.QueryRow(ctx, `INSERT INTO "Video" ("Vid","Referer","CreateTime","UpDateTime") VALUES ($1,$2,$3,$3) RETURNING "Id"`, vid, raw, now).Scan(&id)
	return id, err
}

func (p *Postgres) List(ctx context.Context, vid string, page, size int, descending bool) (domain.Page[domain.Danmaku], error) {
	page, size = normalizePage(page, size)
	where := ""
	args := []any{}
	if vid != "" {
		where = ` WHERE "Vid"=$1`
		args = append(args, vid)
	}
	var total int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "Danmu"`+where, args...).Scan(&total); err != nil {
		return domain.Page[domain.Danmaku]{}, err
	}
	direction := "DESC"
	if !descending {
		direction = "ASC"
	}
	args = append(args, size, size*(page-1))
	query := `SELECT "Id"::text,"Vid","Data",COALESCE("Ip"::text,''),"IsDelete","CreateTime","UpdateTime" FROM "Danmu"` + where + ` ORDER BY "CreateTime" ` + direction + fmt.Sprintf(" LIMIT $%d OFFSET $%d", len(args)-1, len(args))
	list, err := p.queryDanmaku(ctx, query, args...)
	return domain.Page[domain.Danmaku]{Total: total, List: list}, err
}

func (p *Postgres) Search(ctx context.Context, filter SearchFilter) (domain.Page[domain.Danmaku], error) {
	filter.Page, filter.Size = normalizePage(filter.Page, filter.Size)
	clauses := []string{"TRUE"}
	args := make([]any, 0, 10)
	add := func(clause string, value any) {
		args = append(args, value)
		clauses = append(clauses, fmt.Sprintf(clause, len(args)))
	}
	if filter.Mode != nil {
		add(`COALESCE(NULLIF(COALESCE("Data"->>'Mode',"Data"->>'mode'),''),'0')::integer=$%d`, *filter.Mode)
	}
	if filter.IP != nil {
		add(`"Ip"=$%d::inet`, filter.IP.String())
	}
	if filter.Start != nil {
		add(`"CreateTime">$%d`, *filter.Start)
	}
	if filter.End != nil {
		add(`"CreateTime"<$%d`, *filter.End)
	}
	if filter.Vid != "" {
		add(`"Vid" LIKE '%%' || $%d || '%%'`, filter.Vid)
	}
	if filter.Author != "" {
		add(`COALESCE("Data"->>'Author',"Data"->>'author','') LIKE '%%' || $%d || '%%'`, filter.Author)
	}
	if filter.AuthorID != nil {
		add(`COALESCE(NULLIF(COALESCE("Data"->>'AuthorId',"Data"->>'authorId'),''),'0')::integer=$%d`, *filter.AuthorID)
	}
	if filter.Key != "" {
		add(`COALESCE("Data"->>'Text',"Data"->>'text','') LIKE '%%' || $%d || '%%'`, filter.Key)
	}
	where := " WHERE " + strings.Join(clauses, " AND ")
	var total int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "Danmu"`+where, args...).Scan(&total); err != nil {
		return domain.Page[domain.Danmaku]{}, err
	}
	direction := "DESC"
	if !filter.Descending {
		direction = "ASC"
	}
	args = append(args, filter.Size, filter.Size*(filter.Page-1))
	query := `SELECT "Id"::text,"Vid","Data",COALESCE("Ip"::text,''),"IsDelete","CreateTime","UpdateTime" FROM "Danmu"` + where + ` ORDER BY "UpdateTime" ` + direction + fmt.Sprintf(" LIMIT $%d OFFSET $%d", len(args)-1, len(args))
	list, err := p.queryDanmaku(ctx, query, args...)
	return domain.Page[domain.Danmaku]{Total: total, List: list}, err
}

func (p *Postgres) queryDanmaku(ctx context.Context, query string, args ...any) ([]domain.Danmaku, error) {
	rows, err := p.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	list := make([]domain.Danmaku, 0)
	for rows.Next() {
		item, err := scanDanmaku(rows)
		if err != nil {
			return nil, err
		}
		list = append(list, item)
	}
	return list, rows.Err()
}

func scanDanmaku(row pgx.Row) (domain.Danmaku, error) {
	var item domain.Danmaku
	var raw []byte
	var ip string
	if err := row.Scan(&item.ID, &item.Vid, &raw, &ip, &item.IsDeleted, &item.CreateTime, &item.UpdateTime); err != nil {
		return item, err
	}
	item.Data = domain.NewDanmakuData()
	if err := json.Unmarshal(raw, &item.Data); err != nil {
		return item, err
	}
	if ip != "" {
		item.IP = net.ParseIP(strings.Split(ip, "/")[0])
	}
	return item, nil
}

func (p *Postgres) Vids(ctx context.Context) ([]string, error) {
	rows, err := p.pool.Query(ctx, `SELECT DISTINCT "Vid" FROM "Video"`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := make([]string, 0)
	for rows.Next() {
		var vid string
		if err := rows.Scan(&vid); err != nil {
			return nil, err
		}
		result = append(result, vid)
	}
	return result, rows.Err()
}

func (p *Postgres) Get(ctx context.Context, id string) (*domain.Danmaku, error) {
	if !validUUID(id) {
		item := domain.Danmaku{ID: "00000000-0000-0000-0000-000000000000", Data: domain.NewDanmakuData(), CreateTime: time.Now().UTC(), UpdateTime: time.Now().UTC()}
		return &item, nil
	}
	item, err := scanDanmaku(p.pool.QueryRow(ctx, `SELECT "Id"::text,"Vid","Data",COALESCE("Ip"::text,''),"IsDelete","CreateTime","UpdateTime" FROM "Danmu" WHERE "Id"=$1`, id))
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var video domain.Video
	var raw []byte
	err = p.pool.QueryRow(ctx, `SELECT v."Id",v."Vid",v."Referer",v."CreateTime",v."UpDateTime" FROM "Video" v JOIN "Danmu" d ON d."VideoId"=v."Id" WHERE d."Id"=$1`, id).Scan(&video.ID, &video.Vid, &raw, &video.CreateTime, &video.UpdateTime)
	if err == nil {
		if decodeErr := json.Unmarshal(raw, &video.Referer); decodeErr != nil {
			return nil, decodeErr
		}
		item.Video = &video
	} else if !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	return &item, nil
}

func (p *Postgres) Edit(ctx context.Context, id string, changes domain.DanmakuData, isDeleted bool) (*domain.Danmaku, error) {
	if !validUUID(id) {
		return nil, nil
	}
	current, err := p.Get(ctx, id)
	if err != nil || current == nil {
		return current, err
	}
	current.Data.Time = changes.Time
	current.Data.Mode = changes.Mode
	current.Data.Color = changes.Color
	if changes.Text != nil {
		current.Data.Text = changes.Text
	}
	raw, err := domain.MarshalDBData(current.Data)
	if err != nil {
		return nil, err
	}
	current.IsDeleted = isDeleted
	current.UpdateTime = time.Now().UTC().Truncate(time.Second)
	command, err := p.pool.Exec(ctx, `UPDATE "Danmu" SET "Data"=$2,"IsDelete"=$3,"UpdateTime"=$4 WHERE "Id"=$1`, id, raw, current.IsDeleted, current.UpdateTime)
	if err != nil || command.RowsAffected() == 0 {
		return nil, err
	}
	current.Video = nil
	return current, nil
}

func (p *Postgres) Delete(ctx context.Context, id string) (bool, error) {
	if !validUUID(id) {
		return false, nil
	}
	command, err := p.pool.Exec(ctx, `UPDATE "Danmu" SET "IsDelete"=TRUE,"UpdateTime"=$2 WHERE "Id"=$1`, id, time.Now().UTC().Truncate(time.Second))
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) VerifyPassword(ctx context.Context, name, password string) (bool, int, int, error) {
	var uid, role int
	var stored, salt string
	err := p.pool.QueryRow(ctx, `SELECT "Id","Role","PassWord","Salt" FROM "User" WHERE "Name"=$1 LIMIT 1`, name).Scan(&uid, &role, &stored, &salt)
	if errors.Is(err, pgx.ErrNoRows) {
		return false, 0, 3, nil
	}
	if err != nil {
		return false, 0, 3, err
	}
	if stored == saltedMD5(password, salt) {
		return true, uid, role, nil
	}
	if p.admin.User == name && strings.EqualFold(password, md5String(p.admin.Password)) {
		return true, 0, 1, nil
	}
	return false, 0, 3, nil
}

func (p *Postgres) ChangePassword(ctx context.Context, id int, oldPassword, newPassword string) (bool, error) {
	if strings.TrimSpace(oldPassword) == "" || strings.TrimSpace(newPassword) == "" {
		return false, nil
	}
	var stored, salt string
	err := p.pool.QueryRow(ctx, `SELECT "PassWord","Salt" FROM "User" WHERE "Id"=$1`, id).Scan(&stored, &salt)
	if errors.Is(err, pgx.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if stored != saltedMD5(oldPassword, salt) {
		return false, nil
	}
	newSalt, err := randomString(6)
	if err != nil {
		return false, err
	}
	command, err := p.pool.Exec(ctx, `UPDATE "User" SET "PassWord"=$2,"Salt"=$3,"UpdateTime"=$4 WHERE "Id"=$1`, id, saltedMD5(newPassword, newSalt), newSalt, time.Now().UTC().Truncate(time.Millisecond))
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) ChangeUserInfo(ctx context.Context, id int, name string, email, phone *string) (bool, error) {
	var count int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "User" WHERE "Name"=$1 AND "Id"<>$2`, name, id).Scan(&count); err != nil {
		return false, err
	}
	if count > 0 {
		return false, nil
	}
	command, err := p.pool.Exec(ctx, `UPDATE "User" SET "Name"=COALESCE(NULLIF($2,''),"Name"),"Email"=COALESCE($3,"Email"),"PhoneNumber"=COALESCE($4,"PhoneNumber"),"UpdateTime"=$5 WHERE "Id"=$1`, id, name, email, phone, time.Now().UTC().Truncate(time.Millisecond))
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) User(ctx context.Context, id int) (*domain.User, error) {
	var user domain.User
	err := p.pool.QueryRow(ctx, `SELECT "Id","Name","Role","PhoneNumber","Email","CreateTime","UpdateTime" FROM "User" WHERE "Id"=$1`, id).Scan(&user.ID, &user.Name, &user.Role, &user.PhoneNumber, &user.Email, &user.CreateTime, &user.UpdateTime)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	user.Salt, _ = randomString(6)
	return &user, nil
}

func (p *Postgres) Cache(ctx context.Context, key string, lifetime time.Duration, fetch func(context.Context) ([]byte, error)) ([]byte, error) {
	var id int
	var value []byte
	var timestamp int64
	err := p.pool.QueryRow(ctx, `SELECT "Id","Value","TimeStamp" FROM "HttpClientCache" WHERE "Key"=$1 LIMIT 1`, key).Scan(&id, &value, &timestamp)
	if err == nil && len(value) > 0 && time.Now().Unix()-timestamp <= int64(lifetime.Seconds()) {
		return value, nil
	}
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	value, err = fetch(ctx)
	if err != nil {
		return nil, err
	}
	now := time.Now().Unix()
	if id != 0 {
		_, err = p.pool.Exec(ctx, `UPDATE "HttpClientCache" SET "Value"=$2,"TimeStamp"=$3 WHERE "Id"=$1`, id, value, now)
	} else {
		_, err = p.pool.Exec(ctx, `INSERT INTO "HttpClientCache" ("Key","Value","TimeStamp") VALUES ($1,$2,$3)`, key, value, now)
	}
	return value, err
}

func normalizePage(page, size int) (int, int) {
	if page < 1 {
		page = 1
	}
	if size < 1 {
		size = 30
	}
	return page, size
}

func md5String(value string) string {
	sum := md5.Sum([]byte(value))
	return hex.EncodeToString(sum[:])
}

func saltedMD5(value, salt string) string {
	if salt == "" {
		return md5String(value)
	}
	if len(value) >= 2 {
		value = value[2:]
	}
	return md5String(value + salt)
}

func randomString(length int) (string, error) {
	const alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
	buffer := make([]byte, length)
	raw := make([]byte, length)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	for index := range raw {
		buffer[index] = alphabet[int(raw[index])%len(alphabet)]
	}
	return string(buffer), nil
}

func randomUUID() (string, error) {
	value := make([]byte, 16)
	if _, err := rand.Read(value); err != nil {
		return "", err
	}
	value[6] = (value[6] & 0x0f) | 0x40
	value[8] = (value[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x", value[0:4], value[4:6], value[6:8], value[8:10], value[10:16]), nil
}

func validUUID(value string) bool {
	if len(value) != 36 {
		return false
	}
	for index, char := range value {
		if index == 8 || index == 13 || index == 18 || index == 23 {
			if char != '-' {
				return false
			}
			continue
		}
		if !strings.ContainsRune("0123456789abcdefABCDEF", char) {
			return false
		}
	}
	return true
}

func ParseReferer(raw string) (domain.Referer, error) {
	parsed, err := url.Parse(raw)
	if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
		return domain.Referer{}, errors.New("invalid referer URL")
	}
	port := 0
	if parsed.Port() != "" {
		_, _ = fmt.Sscanf(parsed.Port(), "%d", &port)
	} else if parsed.Scheme == "https" {
		port = 443
	} else if parsed.Scheme == "http" {
		port = 80
	}
	path := parsed.EscapedPath()
	if path == "" {
		path = "/"
	}
	return domain.Referer{Protocol: parsed.Scheme, Host: parsed.Hostname(), Port: port, Path: path, Query: queryWithPrefix(parsed.RawQuery), Fragment: fragmentWithPrefix(parsed.Fragment)}, nil
}

func queryWithPrefix(value string) string {
	if value == "" {
		return ""
	}
	return "?" + value
}

func fragmentWithPrefix(value string) string {
	if value == "" {
		return ""
	}
	return "#" + value
}
