package store

import (
	"context"
	"crypto/md5"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/url"
	"strings"
	"time"

	"git.hanada.info/tamersunion/danmaku/internal/config"
	"git.hanada.info/tamersunion/danmaku/internal/domain"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Postgres struct {
	pool  *pgxpool.Pool
	admin config.AdminSettings
}

const duplicateDanmakuWindow = 30 * time.Second

const duplicateDanmakuQuery = `SELECT EXISTS (
	SELECT 1
	FROM "Danmaku"
	WHERE "Vid"=$1
		AND "Ip" IS NOT DISTINCT FROM $2::inet
		AND md5(COALESCE("Data"->>'Text',''))=md5($3)
		AND COALESCE("Data"->>'Text','')=$3
		AND "CreateTime">=$4
)`

func Open(ctx context.Context, cfg config.Config) (*Postgres, error) {
	poolConfig, err := pgxpool.ParseConfig(cfg.DanmakuSQL.ConnectionString())
	if err != nil {
		return nil, fmt.Errorf("parse PostgreSQL configuration: %w", err)
	}
	poolConfig.MaxConns = cfg.DanmakuSQL.PoolSize
	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		return nil, fmt.Errorf("open PostgreSQL pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("connect to PostgreSQL: %w", err)
	}
	return &Postgres{pool: pool, admin: cfg.Admin}, nil
}

func (p *Postgres) Close() { p.pool.Close() }

func (p *Postgres) Initialize(ctx context.Context) error {
	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin PostgreSQL schema migration: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	for _, statement := range schemaStatements() {
		if _, err := tx.Exec(ctx, statement); err != nil {
			return fmt.Errorf("initialize PostgreSQL schema: %w", err)
		}
	}

	var count int
	if err := tx.QueryRow(ctx, `SELECT COUNT(*) FROM "User"`).Scan(&count); err != nil {
		return fmt.Errorf("count users: %w", err)
	}
	if count == 0 {
		salt, err := randomString(6)
		if err != nil {
			return err
		}
		now := time.Now().UTC()
		password := saltedMD5(md5String(p.admin.Password), salt)
		_, err = tx.Exec(ctx, `INSERT INTO "User" ("Name", "PassWord", "Salt", "Role", "CreateTime", "UpdateTime") VALUES ($1,$2,$3,1,$4,$4)`, p.admin.User, password, salt, now)
		if err != nil {
			return fmt.Errorf("create initial administrator: %w", err)
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit PostgreSQL schema migration: %w", err)
	}
	return nil
}

func schemaStatements() []string {
	return []string{
		`DO $$ BEGIN
			IF to_regclass('"Danmu"') IS NOT NULL AND to_regclass('"Danmaku"') IS NOT NULL THEN
				RAISE EXCEPTION 'both legacy table "Danmu" and target table "Danmaku" exist; refusing an ambiguous migration';
			ELSIF to_regclass('"Danmu"') IS NOT NULL THEN
				ALTER TABLE "Danmu" RENAME TO "Danmaku";
			END IF;
		END $$`,
		`CREATE TABLE IF NOT EXISTS "User" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"Name" character varying(16) NOT NULL,
			"PassWord" text NOT NULL,
			"Salt" text NOT NULL,
			"Role" integer NOT NULL,
			"Enabled" boolean NOT NULL DEFAULT TRUE,
			"PhoneNumber" text NULL,
			"Email" text NULL,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			"UpdateTime" timestamp(3) without time zone NOT NULL,
			"CASSubject" character varying(128) NULL,
			"CASDisplayName" character varying(240) NULL,
			"CASAvatar" text NULL
		)`,
		`CREATE TABLE IF NOT EXISTS "Video" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"Vid" character varying(36) NOT NULL,
			"Referer" jsonb NULL,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			"UpDateTime" timestamp(3) without time zone NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS "Danmaku" (
			"Id" uuid NOT NULL PRIMARY KEY,
			"Vid" character varying(36) NOT NULL,
			"Data" jsonb NOT NULL,
			"Ip" inet NULL,
			"IsDelete" boolean NOT NULL DEFAULT FALSE,
			"VideoId" integer NULL,
			"CreateTime" timestamp(0) without time zone NOT NULL,
			"UpdateTime" timestamp(0) without time zone NOT NULL,
			CONSTRAINT "FK_Danmaku_Video_VideoId" FOREIGN KEY ("VideoId") REFERENCES "Video" ("Id") ON DELETE RESTRICT
		)`,
		`CREATE TABLE IF NOT EXISTS "HttpClientCache" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"Key" text NOT NULL,
			"Value" bytea NULL,
			"TimeStamp" bigint NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS "BilibiliDanmakuPool" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"BVID" character varying(32) NULL,
			"Page" integer NOT NULL,
			"CID" bigint NOT NULL,
			"LastAttemptTime" timestamp(3) without time zone NULL,
			"LastSyncTime" timestamp(3) without time zone NULL,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			"UpdateTime" timestamp(3) without time zone NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS "BilibiliDanmaku" (
			"Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"PoolId" integer NOT NULL,
			"Timestamp" bigint NOT NULL,
			"Content" text NOT NULL,
			"ContentHash" character(64) NOT NULL,
			"Data" jsonb NOT NULL,
			"IsBlocked" boolean NOT NULL DEFAULT FALSE,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			"UpdateTime" timestamp(3) without time zone NOT NULL,
			CONSTRAINT "FK_BilibiliDanmaku_Pool_PoolId" FOREIGN KEY ("PoolId") REFERENCES "BilibiliDanmakuPool" ("Id") ON DELETE CASCADE
		)`,
		`CREATE TABLE IF NOT EXISTS "BilibiliDanmakuKeyword" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"PoolId" integer NULL,
			"Keyword" text NOT NULL,
			"KeywordHash" character(64) NOT NULL,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			CONSTRAINT "FK_BilibiliDanmakuKeyword_Pool_PoolId" FOREIGN KEY ("PoolId") REFERENCES "BilibiliDanmakuPool" ("Id") ON DELETE CASCADE
		)`,
		`CREATE TABLE IF NOT EXISTS "BilibiliDanmakuBinding" (
			"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			"Vid" character varying(36) NOT NULL,
			"PoolId" integer NOT NULL,
			"Offset" double precision NOT NULL DEFAULT 0,
			"CreateTime" timestamp(3) without time zone NOT NULL,
			"UpdateTime" timestamp(3) without time zone NOT NULL,
			CONSTRAINT "FK_BilibiliDanmakuBinding_Pool_PoolId" FOREIGN KEY ("PoolId") REFERENCES "BilibiliDanmakuPool" ("Id") ON DELETE CASCADE
		)`,
		`ALTER TABLE "BilibiliDanmakuPool" ALTER COLUMN "BVID" DROP NOT NULL`,
		`DO $$ BEGIN IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='UpDateTime') THEN ALTER TABLE "User" RENAME COLUMN "UpDateTime" TO "UpdateTime"; END IF; END $$`,
		`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "CASSubject" character varying(128) NULL`,
		`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "CASDisplayName" character varying(240) NULL`,
		`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "CASAvatar" text NULL`,
		`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "Enabled" boolean NOT NULL DEFAULT TRUE`,
		`DO $$ BEGIN
			IF EXISTS(SELECT 1 FROM pg_constraint WHERE conname='FK_Danmu_Video_VideoId' AND conrelid='"Danmaku"'::regclass)
			AND EXISTS(SELECT 1 FROM pg_constraint WHERE conname='FK_Danmaku_Video_VideoId' AND conrelid='"Danmaku"'::regclass) THEN
				RAISE EXCEPTION 'both legacy and target Danmaku foreign key names exist; refusing an ambiguous migration';
			ELSIF EXISTS(SELECT 1 FROM pg_constraint WHERE conname='FK_Danmu_Video_VideoId' AND conrelid='"Danmaku"'::regclass) THEN
				ALTER TABLE "Danmaku" RENAME CONSTRAINT "FK_Danmu_Video_VideoId" TO "FK_Danmaku_Video_VideoId";
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF to_regclass('"IX_Danmu_Vid_IsDelete"') IS NOT NULL AND to_regclass('"IX_Danmaku_Vid_IsDelete"') IS NOT NULL THEN
				RAISE EXCEPTION 'both legacy and target Danmaku Vid index names exist; refusing an ambiguous migration';
			ELSIF to_regclass('"IX_Danmu_Vid_IsDelete"') IS NOT NULL THEN
				ALTER INDEX "IX_Danmu_Vid_IsDelete" RENAME TO "IX_Danmaku_Vid_IsDelete";
			END IF;
			IF to_regclass('"IX_Danmu_VideoId"') IS NOT NULL AND to_regclass('"IX_Danmaku_VideoId"') IS NOT NULL THEN
				RAISE EXCEPTION 'both legacy and target Danmaku VideoId index names exist; refusing an ambiguous migration';
			ELSIF to_regclass('"IX_Danmu_VideoId"') IS NOT NULL THEN
				ALTER INDEX "IX_Danmu_VideoId" RENAME TO "IX_Danmaku_VideoId";
			END IF;
		END $$`,
		`CREATE INDEX IF NOT EXISTS "IX_Danmaku_Vid_IsDelete" ON "Danmaku" ("Vid", "IsDelete")`,
		`CREATE INDEX IF NOT EXISTS "IX_Danmaku_VideoId" ON "Danmaku" ("VideoId")`,
		`CREATE INDEX IF NOT EXISTS "IX_Danmaku_DuplicateGuard" ON "Danmaku" ("Vid", "Ip", (md5(COALESCE("Data"->>'Text',''))), "CreateTime")`,
		`CREATE INDEX IF NOT EXISTS "IX_HttpClientCache_Key" ON "HttpClientCache" USING hash ("Key")`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "UX_User_CASSubject" ON "User" ("CASSubject") WHERE "CASSubject" IS NOT NULL`,
		`DROP INDEX IF EXISTS "UX_BilibiliDanmakuPool_BVID_Page"`,
		`CREATE INDEX IF NOT EXISTS "IX_BilibiliDanmakuPool_BVID_Page" ON "BilibiliDanmakuPool" ("BVID", "Page") WHERE "BVID" IS NOT NULL`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "UX_BilibiliDanmakuPool_CID" ON "BilibiliDanmakuPool" ("CID")`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "UX_BilibiliDanmaku_Pool_Timestamp_ContentHash" ON "BilibiliDanmaku" ("PoolId", "Timestamp", "ContentHash")`,
		`CREATE INDEX IF NOT EXISTS "IX_BilibiliDanmaku_Pool_IsBlocked" ON "BilibiliDanmaku" ("PoolId", "IsBlocked")`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "UX_BilibiliDanmakuKeyword_Global" ON "BilibiliDanmakuKeyword" ("KeywordHash") WHERE "PoolId" IS NULL`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "UX_BilibiliDanmakuKeyword_Pool" ON "BilibiliDanmakuKeyword" ("PoolId", "KeywordHash") WHERE "PoolId" IS NOT NULL`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "UX_BilibiliDanmakuBinding_Vid_Pool" ON "BilibiliDanmakuBinding" ("Vid", "PoolId")`,
		`CREATE INDEX IF NOT EXISTS "IX_BilibiliDanmakuBinding_Vid" ON "BilibiliDanmakuBinding" ("Vid")`,
	}
}

func (p *Postgres) QueryByVid(ctx context.Context, vid string) ([]domain.DanmakuData, error) {
	rows, err := p.pool.Query(ctx, `SELECT "Data" FROM "Danmaku" WHERE "Vid"=$1 AND NOT "IsDelete"`, vid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := make([]domain.DanmakuData, 0)
	for rows.Next() {
		var raw []byte
		if err := rows.Scan(&raw); err != nil {
			return nil, err
		}
		data := domain.NewDanmakuData()
		if err := json.Unmarshal(raw, &data); err != nil {
			return nil, fmt.Errorf("decode Danmaku.Data: %w", err)
		}
		result = append(result, data)
	}
	return result, rows.Err()
}

func (p *Postgres) Insert(ctx context.Context, vid string, data domain.DanmakuData, ip net.IP, referer domain.Referer) (bool, error) {
	now := time.Now().UTC().Truncate(time.Second)
	var ipValue any
	if ip != nil {
		ipValue = ip.String()
	}
	text := ""
	if data.Text != nil {
		text = *data.Text
	}

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return false, fmt.Errorf("begin Danmaku insert: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock($1)`, duplicateDanmakuAdvisoryKey(vid, ip, text)); err != nil {
		return false, fmt.Errorf("lock duplicate Danmaku submissions: %w", err)
	}
	var duplicate bool
	if err := tx.QueryRow(ctx, duplicateDanmakuQuery, vid, ipValue, text, now.Add(-duplicateDanmakuWindow)).Scan(&duplicate); err != nil {
		return false, fmt.Errorf("check duplicate Danmaku submission: %w", err)
	}
	if duplicate {
		if err := tx.Commit(ctx); err != nil {
			return false, fmt.Errorf("commit duplicate Danmaku check: %w", err)
		}
		return false, nil
	}

	videoID, err := p.findOrInsertVideo(ctx, tx, vid, referer)
	if err != nil {
		return false, err
	}
	raw, err := domain.MarshalDBData(data)
	if err != nil {
		return false, err
	}
	id, err := randomUUID()
	if err != nil {
		return false, err
	}
	if _, err := tx.Exec(ctx, `INSERT INTO "Danmaku" ("Id","Vid","Data","Ip","IsDelete","VideoId","CreateTime","UpdateTime") VALUES ($1,$2,$3,$4,FALSE,$5,$6,$6)`, id, vid, raw, ipValue, videoID, now); err != nil {
		return false, err
	}
	if err := tx.Commit(ctx); err != nil {
		return false, fmt.Errorf("commit Danmaku insert: %w", err)
	}
	return true, nil
}

func duplicateDanmakuAdvisoryKey(vid string, ip net.IP, text string) int64 {
	ipText := ""
	if ip != nil {
		ipText = ip.String()
	}
	hash := sha256.New()
	var size [8]byte
	for _, value := range []string{"danmaku:duplicate:v1", ipText, vid, text} {
		binary.BigEndian.PutUint64(size[:], uint64(len(value)))
		_, _ = hash.Write(size[:])
		_, _ = hash.Write([]byte(value))
	}
	sum := hash.Sum(nil)
	return int64(binary.BigEndian.Uint64(sum[:8]))
}

func (p *Postgres) findOrInsertVideo(ctx context.Context, tx pgx.Tx, vid string, referer domain.Referer) (int, error) {
	rows, err := tx.Query(ctx, `SELECT "Id", "Referer" FROM "Video" WHERE "Vid"=$1`, vid)
	if err != nil {
		return 0, err
	}
	for rows.Next() {
		var id int
		var raw []byte
		if err := rows.Scan(&id, &raw); err != nil {
			return 0, err
		}
		var existing domain.Referer
		if json.Unmarshal(raw, &existing) == nil && existing.Protocol == referer.Protocol && existing.Host == referer.Host && existing.Path == referer.Path && existing.Query == referer.Query {
			rows.Close()
			return id, nil
		}
	}
	err = rows.Err()
	rows.Close()
	if err != nil {
		return 0, err
	}
	raw, err := domain.MarshalDBReferer(referer)
	if err != nil {
		return 0, err
	}
	now := time.Now().UTC().Truncate(time.Millisecond)
	var id int
	err = tx.QueryRow(ctx, `INSERT INTO "Video" ("Vid","Referer","CreateTime","UpDateTime") VALUES ($1,$2,$3,$3) RETURNING "Id"`, vid, raw, now).Scan(&id)
	return id, err
}

func (p *Postgres) List(ctx context.Context, vid string, page, size int, descending bool) (domain.Page[domain.Danmaku], error) {
	page, size = normalizePage(page, size)
	where := ""
	args := []any{}
	if vid != "" {
		where = ` WHERE "Vid"=$1`
		args = append(args, vid)
	}
	var total int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "Danmaku"`+where, args...).Scan(&total); err != nil {
		return domain.Page[domain.Danmaku]{}, err
	}
	direction := "DESC"
	if !descending {
		direction = "ASC"
	}
	args = append(args, size, size*(page-1))
	query := `SELECT "Id"::text,"Vid","Data",COALESCE("Ip"::text,''),"IsDelete","CreateTime","UpdateTime" FROM "Danmaku"` + where + ` ORDER BY "CreateTime" ` + direction + fmt.Sprintf(" LIMIT $%d OFFSET $%d", len(args)-1, len(args))
	list, err := p.queryDanmaku(ctx, query, args...)
	return domain.Page[domain.Danmaku]{Total: total, List: list}, err
}

func (p *Postgres) Search(ctx context.Context, filter SearchFilter) (domain.Page[domain.Danmaku], error) {
	filter.Page, filter.Size = normalizePage(filter.Page, filter.Size)
	clauses := []string{"TRUE"}
	args := make([]any, 0, 10)
	add := func(clause string, value any) {
		args = append(args, value)
		clauses = append(clauses, fmt.Sprintf(clause, len(args)))
	}
	if filter.Mode != nil {
		add(`COALESCE(NULLIF(COALESCE("Data"->>'Mode',"Data"->>'mode'),''),'0')::integer=$%d`, *filter.Mode)
	}
	if filter.IP != nil {
		add(`"Ip"=$%d::inet`, filter.IP.String())
	}
	if filter.Start != nil {
		add(`"CreateTime">$%d`, *filter.Start)
	}
	if filter.End != nil {
		add(`"CreateTime"<$%d`, *filter.End)
	}
	if filter.Vid != "" {
		add(`"Vid" LIKE '%%' || $%d || '%%'`, filter.Vid)
	}
	if filter.Author != "" {
		add(`COALESCE("Data"->>'Author',"Data"->>'author','') LIKE '%%' || $%d || '%%'`, filter.Author)
	}
	if filter.AuthorID != nil {
		add(`COALESCE(NULLIF(COALESCE("Data"->>'AuthorId',"Data"->>'authorId'),''),'0')::integer=$%d`, *filter.AuthorID)
	}
	if filter.Key != "" {
		add(`COALESCE("Data"->>'Text',"Data"->>'text','') LIKE '%%' || $%d || '%%'`, filter.Key)
	}
	where := " WHERE " + strings.Join(clauses, " AND ")
	var total int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "Danmaku"`+where, args...).Scan(&total); err != nil {
		return domain.Page[domain.Danmaku]{}, err
	}
	direction := "DESC"
	if !filter.Descending {
		direction = "ASC"
	}
	args = append(args, filter.Size, filter.Size*(filter.Page-1))
	query := `SELECT "Id"::text,"Vid","Data",COALESCE("Ip"::text,''),"IsDelete","CreateTime","UpdateTime" FROM "Danmaku"` + where + ` ORDER BY "UpdateTime" ` + direction + fmt.Sprintf(" LIMIT $%d OFFSET $%d", len(args)-1, len(args))
	list, err := p.queryDanmaku(ctx, query, args...)
	return domain.Page[domain.Danmaku]{Total: total, List: list}, err
}

func (p *Postgres) queryDanmaku(ctx context.Context, query string, args ...any) ([]domain.Danmaku, error) {
	rows, err := p.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	list := make([]domain.Danmaku, 0)
	for rows.Next() {
		item, err := scanDanmaku(rows)
		if err != nil {
			return nil, err
		}
		list = append(list, item)
	}
	return list, rows.Err()
}

func scanDanmaku(row pgx.Row) (domain.Danmaku, error) {
	var item domain.Danmaku
	var raw []byte
	var ip string
	if err := row.Scan(&item.ID, &item.Vid, &raw, &ip, &item.IsDeleted, &item.CreateTime, &item.UpdateTime); err != nil {
		return item, err
	}
	item.Data = domain.NewDanmakuData()
	if err := json.Unmarshal(raw, &item.Data); err != nil {
		return item, err
	}
	if ip != "" {
		item.IP = net.ParseIP(strings.Split(ip, "/")[0])
	}
	return item, nil
}

func (p *Postgres) Vids(ctx context.Context) ([]string, error) {
	rows, err := p.pool.Query(ctx, `SELECT DISTINCT "Vid" FROM "Video"`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := make([]string, 0)
	for rows.Next() {
		var vid string
		if err := rows.Scan(&vid); err != nil {
			return nil, err
		}
		result = append(result, vid)
	}
	return result, rows.Err()
}

func (p *Postgres) Get(ctx context.Context, id string) (*domain.Danmaku, error) {
	if !validUUID(id) {
		item := domain.Danmaku{ID: "00000000-0000-0000-0000-000000000000", Data: domain.NewDanmakuData(), CreateTime: time.Now().UTC(), UpdateTime: time.Now().UTC()}
		return &item, nil
	}
	item, err := scanDanmaku(p.pool.QueryRow(ctx, `SELECT "Id"::text,"Vid","Data",COALESCE("Ip"::text,''),"IsDelete","CreateTime","UpdateTime" FROM "Danmaku" WHERE "Id"=$1`, id))
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var video domain.Video
	var raw []byte
	err = p.pool.QueryRow(ctx, `SELECT v."Id",v."Vid",v."Referer",v."CreateTime",v."UpDateTime" FROM "Video" v JOIN "Danmaku" d ON d."VideoId"=v."Id" WHERE d."Id"=$1`, id).Scan(&video.ID, &video.Vid, &raw, &video.CreateTime, &video.UpdateTime)
	if err == nil {
		if decodeErr := json.Unmarshal(raw, &video.Referer); decodeErr != nil {
			return nil, decodeErr
		}
		item.Video = &video
	} else if !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	return &item, nil
}

func (p *Postgres) Edit(ctx context.Context, id string, changes domain.DanmakuData, isDeleted bool) (*domain.Danmaku, error) {
	if !validUUID(id) {
		return nil, nil
	}
	current, err := p.Get(ctx, id)
	if err != nil || current == nil {
		return current, err
	}
	current.Data.Time = changes.Time
	current.Data.Mode = changes.Mode
	current.Data.Color = changes.Color
	if changes.Text != nil {
		current.Data.Text = changes.Text
	}
	raw, err := domain.MarshalDBData(current.Data)
	if err != nil {
		return nil, err
	}
	current.IsDeleted = isDeleted
	current.UpdateTime = time.Now().UTC().Truncate(time.Second)
	command, err := p.pool.Exec(ctx, `UPDATE "Danmaku" SET "Data"=$2,"IsDelete"=$3,"UpdateTime"=$4 WHERE "Id"=$1`, id, raw, current.IsDeleted, current.UpdateTime)
	if err != nil || command.RowsAffected() == 0 {
		return nil, err
	}
	current.Video = nil
	return current, nil
}

func (p *Postgres) Delete(ctx context.Context, id string) (bool, error) {
	if !validUUID(id) {
		return false, nil
	}
	command, err := p.pool.Exec(ctx, `UPDATE "Danmaku" SET "IsDelete"=TRUE,"UpdateTime"=$2 WHERE "Id"=$1`, id, time.Now().UTC().Truncate(time.Second))
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) VerifyPassword(ctx context.Context, name, password string) (bool, int, int, error) {
	var uid, role int
	var enabled bool
	var stored, salt string
	err := p.pool.QueryRow(ctx, `SELECT "Id","Role","PassWord","Salt","Enabled" FROM "User" WHERE "Name"=$1 LIMIT 1`, name).Scan(&uid, &role, &stored, &salt, &enabled)
	if errors.Is(err, pgx.ErrNoRows) {
		if configuredAdminMatches(p.admin, name, password) {
			return true, 0, 1, nil
		}
		return false, 0, 3, nil
	}
	if err != nil {
		return false, 0, 3, err
	}
	if enabled && stored == saltedMD5(password, salt) {
		return true, uid, role, nil
	}
	if configuredAdminMatches(p.admin, name, password) {
		return true, 0, 1, nil
	}
	return false, 0, 3, nil
}

func configuredAdminMatches(admin config.AdminSettings, name, password string) bool {
	return admin.User != "" && admin.Password != "" &&
		admin.User == name && strings.EqualFold(password, md5String(admin.Password))
}

func (p *Postgres) ChangePassword(ctx context.Context, id int, oldPassword, newPassword string) (bool, error) {
	if strings.TrimSpace(oldPassword) == "" || strings.TrimSpace(newPassword) == "" {
		return false, nil
	}
	var stored, salt string
	err := p.pool.QueryRow(ctx, `SELECT "PassWord","Salt" FROM "User" WHERE "Id"=$1`, id).Scan(&stored, &salt)
	if errors.Is(err, pgx.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if stored != saltedMD5(oldPassword, salt) {
		return false, nil
	}
	newSalt, err := randomString(6)
	if err != nil {
		return false, err
	}
	command, err := p.pool.Exec(ctx, `UPDATE "User" SET "PassWord"=$2,"Salt"=$3,"UpdateTime"=$4 WHERE "Id"=$1`, id, saltedMD5(newPassword, newSalt), newSalt, time.Now().UTC().Truncate(time.Millisecond))
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) ChangeUserInfo(ctx context.Context, id int, name string, email, phone *string) (bool, error) {
	var count int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "User" WHERE "Name"=$1 AND "Id"<>$2`, name, id).Scan(&count); err != nil {
		return false, err
	}
	if count > 0 {
		return false, nil
	}
	command, err := p.pool.Exec(ctx, `UPDATE "User" SET "Name"=COALESCE(NULLIF($2,''),"Name"),"Email"=COALESCE($3,"Email"),"PhoneNumber"=COALESCE($4,"PhoneNumber"),"UpdateTime"=$5 WHERE "Id"=$1`, id, name, email, phone, time.Now().UTC().Truncate(time.Millisecond))
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) User(ctx context.Context, id int) (*domain.User, error) {
	user, err := scanUser(p.pool.QueryRow(ctx, `SELECT "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar" FROM "User" WHERE "Id"=$1`, id))
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	user.Salt, _ = randomString(6)
	return user, nil
}

func (p *Postgres) Users(ctx context.Context, filter UserFilter) (domain.Page[domain.User], error) {
	page, size := normalizePage(filter.Page, filter.Size)
	where := make([]string, 0, 2)
	args := make([]any, 0, 4)
	if query := strings.TrimSpace(filter.Query); query != "" {
		args = append(args, "%"+query+"%")
		where = append(where, fmt.Sprintf(`("Name" ILIKE $%d OR COALESCE("CASDisplayName",'') ILIKE $%d OR COALESCE("Email",'') ILIKE $%d)`, len(args), len(args), len(args)))
	}
	switch filter.Role {
	case "administrator":
		where = append(where, `"Role"=1`)
	case "danmaku_manager":
		where = append(where, `"Role"=2`)
	case "user":
		where = append(where, `"Role"=3`)
	}
	clause := ""
	if len(where) > 0 {
		clause = " WHERE " + strings.Join(where, " AND ")
	}
	var total int
	if err := p.pool.QueryRow(ctx, `SELECT COUNT(*) FROM "User"`+clause, args...).Scan(&total); err != nil {
		return domain.Page[domain.User]{}, err
	}
	args = append(args, size, (page-1)*size)
	rows, err := p.pool.Query(ctx, `SELECT "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar" FROM "User"`+clause+fmt.Sprintf(` ORDER BY "Id" DESC LIMIT $%d OFFSET $%d`, len(args)-1, len(args)), args...)
	if err != nil {
		return domain.Page[domain.User]{}, err
	}
	defer rows.Close()
	users := make([]domain.User, 0, size)
	for rows.Next() {
		user, err := scanUser(rows)
		if err != nil {
			return domain.Page[domain.User]{}, err
		}
		users = append(users, *user)
	}
	if err := rows.Err(); err != nil {
		return domain.Page[domain.User]{}, err
	}
	return domain.Page[domain.User]{Total: total, List: users}, nil
}

func (p *Postgres) CreateUser(ctx context.Context, input UserCreate) (*domain.User, error) {
	input.Name = strings.TrimSpace(input.Name)
	if input.Name == "" || len([]rune(input.Name)) > 16 || len([]rune(input.Password)) < 6 || len([]rune(input.Password)) > 100 || (input.Role != 1 && input.Role != 2 && input.Role != 3) {
		return nil, fmt.Errorf("invalid user fields")
	}
	var existingID int
	err := p.pool.QueryRow(ctx, `SELECT "Id" FROM "User" WHERE lower("Name")=lower($1) LIMIT 1`, input.Name).Scan(&existingID)
	if err == nil {
		return nil, ErrUserNameConflict
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	salt, err := randomString(12)
	if err != nil {
		return nil, err
	}
	now := time.Now().UTC().Truncate(time.Millisecond)
	return scanUser(p.pool.QueryRow(ctx, `INSERT INTO "User" ("Name","PassWord","Salt","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime") VALUES ($1,$2,$3,$4,TRUE,NULLIF($5,''),NULLIF($6,''),$7,$7) RETURNING "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar"`, input.Name, saltedMD5(md5String(input.Password), salt), salt, input.Role, strings.TrimSpace(input.PhoneNumber), strings.TrimSpace(input.Email), now))
}

func (p *Postgres) UpdateUser(ctx context.Context, id int, input UserUpdate) (*domain.User, error) {
	current, err := p.User(ctx, id)
	if err != nil || current == nil {
		return current, err
	}
	if input.Role != 1 && input.Role != 2 && input.Role != 3 {
		return nil, fmt.Errorf("invalid user role")
	}
	input.Name = strings.TrimSpace(input.Name)
	input.Email = strings.TrimSpace(input.Email)
	input.PhoneNumber = strings.TrimSpace(input.PhoneNumber)
	if current.CASSubject != nil {
		if input.Password != "" || input.Name != current.Name || input.Email != pointerValue(current.Email) || input.PhoneNumber != pointerValue(current.PhoneNumber) {
			return nil, ErrCASProfileReadOnly
		}
		return scanUser(p.pool.QueryRow(ctx, `UPDATE "User" SET "Role"=$2,"UpdateTime"=$3 WHERE "Id"=$1 RETURNING "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar"`, id, input.Role, time.Now().UTC().Truncate(time.Millisecond)))
	}
	if input.Name == "" || len([]rune(input.Name)) > 16 || (input.Password != "" && (len([]rune(input.Password)) < 6 || len([]rune(input.Password)) > 100)) {
		return nil, fmt.Errorf("invalid user fields")
	}
	var conflictingID int
	err = p.pool.QueryRow(ctx, `SELECT "Id" FROM "User" WHERE lower("Name")=lower($1) AND "Id"<>$2 LIMIT 1`, input.Name, id).Scan(&conflictingID)
	if err == nil {
		return nil, ErrUserNameConflict
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	now := time.Now().UTC().Truncate(time.Millisecond)
	if input.Password == "" {
		return scanUser(p.pool.QueryRow(ctx, `UPDATE "User" SET "Name"=$2,"Role"=$3,"PhoneNumber"=NULLIF($4,''),"Email"=NULLIF($5,''),"UpdateTime"=$6 WHERE "Id"=$1 RETURNING "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar"`, id, input.Name, input.Role, input.PhoneNumber, input.Email, now))
	}
	salt, err := randomString(12)
	if err != nil {
		return nil, err
	}
	return scanUser(p.pool.QueryRow(ctx, `UPDATE "User" SET "Name"=$2,"Role"=$3,"PhoneNumber"=NULLIF($4,''),"Email"=NULLIF($5,''),"PassWord"=$6,"Salt"=$7,"UpdateTime"=$8 WHERE "Id"=$1 RETURNING "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar"`, id, input.Name, input.Role, input.PhoneNumber, input.Email, saltedMD5(md5String(input.Password), salt), salt, now))
}

func (p *Postgres) SetUserEnabled(ctx context.Context, id int, enabled bool) (bool, error) {
	command, err := p.pool.Exec(ctx, `UPDATE "User" SET "Enabled"=$2,"UpdateTime"=$3 WHERE "Id"=$1`, id, enabled, time.Now().UTC().Truncate(time.Millisecond))
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) DeleteUser(ctx context.Context, id int) (bool, error) {
	command, err := p.pool.Exec(ctx, `DELETE FROM "User" WHERE "Id"=$1`, id)
	return err == nil && command.RowsAffected() > 0, err
}

func (p *Postgres) UpsertCASUser(ctx context.Context, profile domain.CASProfile, defaultRole int, autoCreate bool) (*domain.User, bool, error) {
	profile.Subject = strings.TrimSpace(profile.Subject)
	profile.UserName = strings.TrimSpace(profile.UserName)
	if profile.Subject == "" || profile.UserName == "" || len([]rune(profile.Subject)) > 128 || len([]rune(profile.UserName)) > 16 {
		return nil, false, fmt.Errorf("invalid CAS identity: subject and username are required and must fit the database schema")
	}
	if defaultRole != 1 && defaultRole != 2 && defaultRole != 3 {
		return nil, false, fmt.Errorf("invalid CAS default role %d", defaultRole)
	}
	profile.DisplayName = truncateRunes(strings.TrimSpace(profile.DisplayName), 240)
	profile.Email = strings.TrimSpace(profile.Email)
	profile.Avatar = strings.TrimSpace(profile.Avatar)

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, false, err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtext($1))`, "danmaku:cas:"+strings.ToLower(profile.UserName)); err != nil {
		return nil, false, err
	}

	user, err := scanUser(tx.QueryRow(ctx, `SELECT "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar" FROM "User" WHERE "CASSubject"=$1 LIMIT 1`, profile.Subject))
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, false, err
	}
	if user != nil {
		if !user.Enabled {
			return nil, false, ErrUserDisabled
		}
		var conflictingID int
		err = tx.QueryRow(ctx, `SELECT "Id" FROM "User" WHERE lower("Name")=lower($1) AND "Id"<>$2 LIMIT 1`, profile.UserName, user.ID).Scan(&conflictingID)
		if err == nil {
			return nil, false, ErrCASIdentityConflict
		}
		if !errors.Is(err, pgx.ErrNoRows) {
			return nil, false, err
		}
		user, err = updateCASUser(ctx, tx, user.ID, profile)
		if err != nil {
			return nil, false, err
		}
		if err := tx.Commit(ctx); err != nil {
			return nil, false, err
		}
		return user, false, nil
	}

	user, err = scanUser(tx.QueryRow(ctx, `SELECT "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar" FROM "User" WHERE lower("Name")=lower($1) LIMIT 1`, profile.UserName))
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, false, err
	}
	if user != nil {
		if !user.Enabled {
			return nil, false, ErrUserDisabled
		}
		if user.CASSubject != nil && *user.CASSubject != profile.Subject {
			return nil, false, ErrCASIdentityConflict
		}
		user, err = updateCASUser(ctx, tx, user.ID, profile)
		if err != nil {
			return nil, false, err
		}
		if err := tx.Commit(ctx); err != nil {
			return nil, false, err
		}
		return user, false, nil
	}
	if !autoCreate {
		return nil, false, ErrCASUserNotFound
	}

	randomPassword, err := randomString(48)
	if err != nil {
		return nil, false, err
	}
	salt, err := randomString(12)
	if err != nil {
		return nil, false, err
	}
	now := time.Now().UTC().Truncate(time.Millisecond)
	user, err = scanUser(tx.QueryRow(ctx, `INSERT INTO "User" ("Name","PassWord","Salt","Role","Enabled","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar") VALUES ($1,$2,$3,$4,TRUE,$5,$6,$6,$7,$8,$9) RETURNING "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar"`, profile.UserName, saltedMD5(randomPassword, salt), salt, defaultRole, nullableString(profile.Email), now, profile.Subject, nullableString(profile.DisplayName), nullableString(profile.Avatar)))
	if err != nil {
		return nil, false, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, false, err
	}
	return user, true, nil
}

func updateCASUser(ctx context.Context, tx pgx.Tx, id int, profile domain.CASProfile) (*domain.User, error) {
	return scanUser(tx.QueryRow(ctx, `UPDATE "User" SET "Name"=$2,"Email"=$3,"CASSubject"=$4,"CASDisplayName"=$5,"CASAvatar"=$6,"UpdateTime"=$7 WHERE "Id"=$1 RETURNING "Id","Name","Role","Enabled","PhoneNumber","Email","CreateTime","UpdateTime","CASSubject","CASDisplayName","CASAvatar"`, id, profile.UserName, nullableString(profile.Email), profile.Subject, nullableString(profile.DisplayName), nullableString(profile.Avatar), time.Now().UTC().Truncate(time.Millisecond)))
}

func scanUser(row pgx.Row) (*domain.User, error) {
	var user domain.User
	if err := row.Scan(&user.ID, &user.Name, &user.Role, &user.Enabled, &user.PhoneNumber, &user.Email, &user.CreateTime, &user.UpdateTime, &user.CASSubject, &user.CASDisplayName, &user.CASAvatar); err != nil {
		return nil, err
	}
	return &user, nil
}

func pointerValue(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

func nullableString(value string) any {
	if value == "" {
		return nil
	}
	return value
}

func truncateRunes(value string, max int) string {
	runes := []rune(value)
	if len(runes) <= max {
		return value
	}
	return string(runes[:max])
}

func (p *Postgres) Cache(ctx context.Context, key string, lifetime time.Duration, fetch func(context.Context) ([]byte, error)) ([]byte, error) {
	var id int
	var value []byte
	var timestamp int64
	err := p.pool.QueryRow(ctx, `SELECT "Id","Value","TimeStamp" FROM "HttpClientCache" WHERE "Key"=$1 LIMIT 1`, key).Scan(&id, &value, &timestamp)
	if err == nil && len(value) > 0 && lifetime > 0 && time.Now().Unix()-timestamp <= int64(lifetime.Seconds()) {
		return value, nil
	}
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	staleValue := value
	value, err = fetch(ctx)
	if err != nil {
		if len(staleValue) == 0 {
			return nil, err
		}
		value = staleValue
	}
	if len(value) == 0 && len(staleValue) > 0 {
		value = staleValue
	}
	now := time.Now().Unix()
	if id != 0 {
		_, err = p.pool.Exec(ctx, `UPDATE "HttpClientCache" SET "Value"=$2,"TimeStamp"=$3 WHERE "Id"=$1`, id, value, now)
	} else {
		_, err = p.pool.Exec(ctx, `INSERT INTO "HttpClientCache" ("Key","Value","TimeStamp") VALUES ($1,$2,$3)`, key, value, now)
	}
	return value, err
}

func normalizePage(page, size int) (int, int) {
	if page < 1 {
		page = 1
	}
	if size < 1 {
		size = 30
	}
	return page, size
}

func md5String(value string) string {
	sum := md5.Sum([]byte(value))
	return hex.EncodeToString(sum[:])
}

func saltedMD5(value, salt string) string {
	if salt == "" {
		return md5String(value)
	}
	if len(value) >= 2 {
		value = value[2:]
	}
	return md5String(value + salt)
}

func randomString(length int) (string, error) {
	const alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
	buffer := make([]byte, length)
	raw := make([]byte, length)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	for index := range raw {
		buffer[index] = alphabet[int(raw[index])%len(alphabet)]
	}
	return string(buffer), nil
}

func randomUUID() (string, error) {
	value := make([]byte, 16)
	if _, err := rand.Read(value); err != nil {
		return "", err
	}
	value[6] = (value[6] & 0x0f) | 0x40
	value[8] = (value[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x", value[0:4], value[4:6], value[6:8], value[8:10], value[10:16]), nil
}

func validUUID(value string) bool {
	if len(value) != 36 {
		return false
	}
	for index, char := range value {
		if index == 8 || index == 13 || index == 18 || index == 23 {
			if char != '-' {
				return false
			}
			continue
		}
		if !strings.ContainsRune("0123456789abcdefABCDEF", char) {
			return false
		}
	}
	return true
}

func ParseReferer(raw string) (domain.Referer, error) {
	parsed, err := url.Parse(raw)
	if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
		return domain.Referer{}, errors.New("invalid referer URL")
	}
	port := 0
	if parsed.Port() != "" {
		_, _ = fmt.Sscanf(parsed.Port(), "%d", &port)
	} else if parsed.Scheme == "https" {
		port = 443
	} else if parsed.Scheme == "http" {
		port = 80
	}
	path := parsed.EscapedPath()
	if path == "" {
		path = "/"
	}
	return domain.Referer{Protocol: parsed.Scheme, Host: parsed.Hostname(), Port: port, Path: path, Query: queryWithPrefix(parsed.RawQuery), Fragment: fragmentWithPrefix(parsed.Fragment)}, nil
}

func queryWithPrefix(value string) string {
	if value == "" {
		return ""
	}
	return "?" + value
}

func fragmentWithPrefix(value string) string {
	if value == "" {
		return ""
	}
	return "#" + value
}
